# Generated by Django 4.2.11 on 2024-04-05 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='predictions/')),
                ('predicted_class', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='XAIImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='xai_images/')),
                ('explanation_method', models.CharField(blank=True, max_length=100)),
                ('features_used', models.CharField(blank=True, max_length=100)),
                ('explanation', models.TextField(blank=True)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XAI_traffic_sign_recognition.prediction')),
            ],
        ),
    ]
